SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `Team_member`;
TRUNCATE TABLE `Team`;
TRUNCATE TABLE `Ability_pokemon`;
TRUNCATE TABLE `Move_pokemon`;
TRUNCATE TABLE `Type_pokemon`;
TRUNCATE TABLE `Pokemon`;
TRUNCATE TABLE `User`;
TRUNCATE TABLE `Move`;
TRUNCATE TABLE `Item`;
TRUNCATE TABLE `Ability`;
TRUNCATE TABLE `Nature`;
TRUNCATE TABLE `Type`;

SET FOREIGN_KEY_CHECKS = 1;
